### ISSUE TITLE
df.to_gbq(): InvalidSchema when using if_exists = 'append'

### ISSUE THREAD

**Issue by jaredbgo** [pydata/pandas-gbq#317]
I have a schema for my upload dataframe.

to_gbq() runs successfully if I am replacing the table (if_exists='replace')

to_gbq() fails if I am appending to the BQ table with matching schema (if_exists='append'):

`InvalidSchema: Please verify that the structure and data types in the DataFrame match the schema of the destination table.`

My schemas certainly should not be a problem, I was appending to the same table I just successfully wrote calling to_gbq() with if_exists ='replace' with the same schema dict.

**Comment by ShantanuKumar** [comment]
It makes sense that it works with `replace` because the table is dropped, and the created with the new data. 
In case of `append`, are you sure you're passing the same schema as that of the existing table in bigquery? 
You need to make sure the data types are bigquery data types in your schema dict, not pandas data types. Something like this
```
[
    {
        "name": "event_ts",
        "type": "TIMESTAMP",
        "mode": "REQUIRED"
    },
    {
        "name": "event_type",
        "type": "STRING",
        "mode": "NULLABLE"
    }
]
```

**Comment by jaredbgo** [comment]
The schema dictionary I pass when successfully using 'replace' is the same schema dictionary that fails when calling 'append'. The schema dictionary reflects what is in BigQuery.

The schema dictionary successfully generates the BQ table using 'replace', but fails when appending to that same BQ table when using 'append'.

**Comment by ShantanuKumar** [comment]
This might be related to #315 
I have created open a pull request #318

**Comment by tswast** [comment]
@jaredbgo please provide a code sample with an example DataFrame (and corresponding BQ schema) where this failure occurs. It is possible that #318 will fix this issue.

**Comment by jaredbgo** [comment]
Looks like #318 should fix. Thanks for looking into it!

**Comment by andrewlgood** [comment]
I have this exact issue and it does not appear to be resolved.  

output = [['Test', 'v1', 'cost_center', '123', date(2020, 1, 31), 30.0],
          ['Test', 'v1', 'cost_center', '345', date(2020, 1, 31), 72.0]]
          
headers = ['scenario', 'version', 'entity', 'account', 'period', 'amount']
df_output = pd.DataFrame(output, columns=headers)

dataset_table = 'my_dataset'
project_id ='my_project_id'
table_schema = [{'name':'scenario', 'type':'string'},
                {'name':'version', 'type':'string'},
                {'name':'entity', 'type':'string'},
                {'name':'account', 'type':'string'},
                {'name':'period', 'date':'string'},
                {'name':'amount', 'float':'string'}
]
df_output.to_gbq(destination_table=dataset_table, 
                 project_id= project_id, 
                 if_exists='append',
                 table_schema=table_schema)

It successfully creates the table in BQ the first time.  Then I run the exact same query a second time and I get the 
"pandas_gbq.gbq.InvalidSchema: Please verify that the structure and data types in the DataFrame match the schema of the destination table."

Andrew Good

**Comment by tswast** [comment]
@andrewlgood Are you using the version from GitHub? We haven't released `0.13.2` yet with this fix.

**Comment by andrewlgood** [comment]
I do not think so.  I am using pandas-gbq 0.13.1.  with Python 3.8.2 on a Window 10 machine

**Comment by tswast** [comment]
@andrewlgood I just released https://pypi.org/project/pandas-gbq/0.13.2/, hopefully that solves your issue.

**Comment by andrewlgood** [comment]
Tim,

 

Thank you for working on this.   I just upgraded to pandas-gbq 0.13.2  but still get the error.

 

Here is the code I am using.  I simply drop the table and run the script twice to test.

 

output2 = [['Test', 'v1', 'cost_center', '123', date(2020, 1, 31), 30.0],

          ['Test', 'v1', 'cost_center', '345', date(2020, 1, 31), 72.0]]

 

headers = ['scenario', 'version', 'entity', 'account', 'period', 'amount']

df_output = pd.DataFrame(output2, columns=headers)

 

#dataset_table = 'my_dataset'

#project_id ='my_project_id'

table_schema = [{'name':'scenario', 'type':'string', 'mode':'required'},

                {'name':'version', 'type':'string', 'mode':'required'},

                {'name':'entity', 'type':'string', 'mode':'required'},

                {'name':'account', 'type':'string', 'mode':'required'},

                {'name':'period', 'type':'date', 'mode':'required'},

                {'name':'amount', 'type':'float', 'mode':'required'}

]

df_output.to_gbq(destination_table=dataset_table, 

                 project_id= project_id, 

                 if_exists='append',

                 table_schema=table_schema)

 

 

Andrew

**Comment by andrewlgood** [comment]
Tim,

 

Question was answered on StackOverflow.  The ‘type’=’FLOAT’ must be capitalized (same for string and date).  

 

Thank you for looking into this.

 

Andrew
