### ISSUE TITLE
Bug in if_exists='replace'

### ISSUE THREAD

**Issue by jstypka** [pydata/pandas-gbq#91]
Hey, we're running into trouble with overwriting tables. When we want to overwrite an existing table, the table is recreated (you can see by the modification date), but nothing is inserted and it's left empty.

Here's the code to reproduce it:
```python
> df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
> df.to_gbq('tmp.table', 'my-project', if_exists='replace') # table doesn't exist yet
Streaming Insert is 100% Complete
 # The table was successfully created and there is data in the streaming buffer
> df.to_gbq('tmp.table', 'my-project', if_exists='replace')
Streaming Insert is 100% Complete
# Table was recreated but it's now empty
```

The streaming is successful both times.
The tables have the same schema and no error about schema is displayed.
After the first write, the table seems empty but there's data in the streaming buffer that you can query. After the second write, it's completely empty.

**pandas-gbq version:** 0.2.0
**Pandas version:** 0.20.3
**OS:** macOS High Sierra
**Python:** 2.7.10

Let me know if I can provide more info!

**Comment by mremes-ng** [comment]
This is a bug in BigQuery API of which I’ve already created in the issue tracker. The data will eventually appear after about an hour.

It seems it should be fixed already:
https://issuetracker.google.com/issues/62160611

**Comment by jstypka** [comment]
thanks for the super fast response @mremes-ng! It looks very similar, you're right, but it's clearly not fixed. Do you think the partitioning of the dataset can have anything to do with it?

**Comment by tswast** [comment]
This issue should no longer happen now that `to_gbq` uses load jobs to upload data.
